version: '3.6'

services:
  neo4j:
    image: neo4j:4.4
    volumes:
      - './data:/data:rw'
    ports:
      - 7474:7474
      - 7687:7687
    environment:
      - NEO4J_AUTH=neo4j/letmein

networks:
  main:
