version: '3.6'

services:

  neo4j:
    build: ./
    volumes:
      - "./data:/data:rw"
    ports:
      - 7474:7474
      - 7687:7687
    environment:
      - VIRTUAL_HOST=neo4j
      - NEO4J_dbms_security_procedures_unrestricted=apoc.*
      - NEO4J_apoc_import_file_enabled=true
      - NEO4J_apoc_export_file_enabled=true
      - NEO4J_dbms_shell_enabled=true
    networks:
      main:
        aliases:
          - neo4j

networks:
  main:
